### ISSUE TITLE
Consorsbank, ING: Sample Code not working for me

### ISSUE THREAD

**Issue by maxbethke** [raphaelm/python-fints#130]
**Describe the bug**
I am sure this is more an environment problem than a bug, but I get an FinTSClientPINError after entering my PIN when trying to initiate a dialog

**Bank I tested this with*
Name of the banks: ING, Consorsbank
FinTS URLs: https://fints.ing.de/fints, https://brokerage-hbci.consorsbank.de/hbci

**Expected behavior**
I should be prompted for a TAN, or get to select the account or operation.

**Code required to reproduce**
https://python-fints.readthedocs.io/en/latest/trouble.html
The only things I changed were the BLZ, USER and ENDPOINT

**Log output / error message**
```
python3 main.py
PIN: 
WARNING:fints.client:You should register your program with the ZKA and pass your own product_id as a parameter.
DEBUG:fints.connection:Sending >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
	fints.message.FinTSCustomerMessage([
	    fints.segments.message.HNHBK3( # Nachrichtenkopf
	        header = fints.formals.SegmentHeader('HNHBK', 1, 3), # Segmentkopf
	        message_size = 386, # Größe der Nachricht (nach Verschlüsselung und Komprimierung)
	        hbci_version = 300, # HBCI-Version
	        dialog_id = '0', # Dialog-ID
	        message_number = 1, # Nachrichtennummer
	    ),
	    fints.segments.message.HNVSK3( # Verschlüsselungskopf, version 3
	        header = fints.formals.SegmentHeader('HNVSK', 998, 3), # Segmentkopf
	        security_profile = fints.formals.SecurityProfile( # Sicherheitsprofil
	                security_method = fints.formals.SecurityMethod.PIN, # Sicherheitsverfahren
	                security_method_version = 1, # Version des Sicherheitsverfahrens
	            ),
	        security_function = '998', # Sicherheitsfunktion, kodiert
	        security_role = fints.formals.SecurityRole.ISS, # Rolle des Sicherheitslieferanten, kodiert: Erfasser, Erstsignatur
	        security_identification_details = fints.formals.SecurityIdentificationDetails( # Sicherheitsidentifikation, Details
	                identified_role = fints.formals.IdentifiedRole.MS, # Message Sender
	                cid = None,
	                identifier = '0',
	            ),
	        security_datetime = fints.formals.SecurityDateTime( # Sicherheitsdatum und -uhrzeit
	                date_time_type = fints.formals.DateTimeType.STS, # Sicherheitszeitstempel
	                date = datetime.date(2021, 4, 29),
	                time = datetime.time(12, 31, 7, 721065),
	            ),
	        encryption_algorithm = fints.formals.EncryptionAlgorithm( # Verschlüsselungsalgorithmus
	                usage_encryption = fints.formals.UsageEncryption.OSY, # Owner Symmetric
	                operation_mode = fints.formals.OperationMode.CBC, # Cipher Block Chaining
	                encryption_algorithm = fints.formals.EncryptionAlgorithmCoded.TWOKEY3DES, # 2-Key-Triple-DES
	                algorithm_parameter_value = b'\x00\x00\x00\x00\x00\x00\x00\x00',
	                algorithm_parameter_name = fints.formals.AlgorithmParameterName.KYE, # Symmetrischer Schlüssel, verschlüsselt mit symmetrischem Schlüssel
	                algorithm_parameter_iv_name = fints.formals.AlgorithmParameterIVName.IVC, # Initialization value, clear text
	            ),
	        key_name = fints.formals.KeyName( # Schlüsselname
	                bank_identifier = fints.formals.BankIdentifier(
	                        country_identifier = '280',
	                        bank_code = '76030080',
	                    ),
	                user_id = '250075751',
	                key_type = fints.formals.KeyType.V, # Schlüsselart: Chiffrierschlüssel
	                key_number = 0,
	                key_version = 0,
	            ),
	        compression_function = fints.formals.CompressionFunction.NULL, # Komprimierungsfunktion: Keine Kompression
	    ),
	    fints.segments.message.HNVSD1( # Verschlüsselte Daten, version 1
	        header = fints.formals.SegmentHeader('HNVSD', 999, 1), # Segmentkopf
	        data = fints.types.SegmentSequence([ # Daten, verschlüsselt
	                fints.segments.message.HNSHK4( # Signaturkopf, version 4
	                    header = fints.formals.SegmentHeader('HNSHK', 2, 4), # Segmentkopf
	                    security_profile = fints.formals.SecurityProfile( # Sicherheitsprofil
	                            security_method = fints.formals.SecurityMethod.PIN, # Sicherheitsverfahren
	                            security_method_version = 1, # Version des Sicherheitsverfahrens
	                        ),
	                    security_function = '999', # Sicherheitsfunktion, kodiert
	                    security_reference = '2460121', # Sicherheitskontrollreferenz
	                    security_application_area = fints.formals.SecurityApplicationArea.SHM, # Bereich der Sicherheitsapplikation, kodiert: Signaturkopf und HBCI-Nutzdaten
	                    security_role = fints.formals.SecurityRole.ISS, # Rolle des Sicherheitslieferanten, kodiert: Erfasser, Erstsignatur
	                    security_identification_details = fints.formals.SecurityIdentificationDetails( # Sicherheitsidentifikation, Details
	                            identified_role = fints.formals.IdentifiedRole.MS, # Message Sender
	                            cid = None,
	                            identifier = '0',
	                        ),
	                    security_reference_number = 1, # Sicherheitsreferenznummer
	                    security_datetime = fints.formals.SecurityDateTime( # Sicherheitsdatum und -uhrzeit
	                            date_time_type = fints.formals.DateTimeType.STS, # Sicherheitszeitstempel
	                            date = datetime.date(2021, 4, 29),
	                            time = datetime.time(12, 31, 7, 720444),
	                        ),
	                    hash_algorithm = fints.formals.HashAlgorithm( # Hashalgorithmus
	                            usage_hash = '1',
	                            hash_algorithm = '999',
	                            algorithm_parameter_name = '1',
	                        ),
	                    signature_algorithm = fints.formals.SignatureAlgorithm( # Signaturalgorithmus
	                            usage_signature = '6',
	                            signature_algorithm = '10',
	                            operation_mode = '16',
	                        ),
	                    key_name = fints.formals.KeyName( # Schlüsselname
	                            bank_identifier = fints.formals.BankIdentifier(
	                                    country_identifier = '280',
	                                    bank_code = '76030080',
	                                ),
	                            user_id = '250075751',
	                            key_type = fints.formals.KeyType.S, # Schlüsselart: Signierschlüssel
	                            key_number = 0,
	                            key_version = 0,
	                        ),
	                ),
	                fints.segments.auth.HKIDN2( # Identifikation, version 2
	                    header = fints.formals.SegmentHeader('HKIDN', 3, 2), # Segmentkopf
	                    bank_identifier = fints.formals.BankIdentifier( # Kreditinstitutskennung
	                            country_identifier = '280',
	                            bank_code = '76030080',
	                        ),
	                    customer_id = '250075751', # Kunden-ID
	                    system_id = '0', # Kundensystem-ID
	                    system_id_status = fints.formals.SystemIDStatus.ID_NECESSARY, # Kundensystem-Status: Kundensystem-ID wird benötigt
	                ),
	                fints.segments.auth.HKVVB3( # Verarbeitungsvorbereitung, version 3
	                    header = fints.formals.SegmentHeader('HKVVB', 4, 3), # Segmentkopf
	                    bpd_version = 0, # BPD-Version
	                    upd_version = 0, # UPD-Version
	                    language = fints.formals.Language2.DE, # Dialogsprache: Deutsch, 'de', Subset Deutsch, Codeset 1 (Latin 1)
	                    product_name = 'DC333D745719C4BD6A6F9DB6A', # Produktbezeichnung
	                    product_version = '3.0.1', # Produktversion
	                ),
	                fints.segments.dialog.HKSYN3( # Synchronisierung, version 3
	                    header = fints.formals.SegmentHeader('HKSYN', 5, 3), # Segmentkopf
	                    synchronization_mode = fints.formals.SynchronizationMode.NEW_SYSTEM_ID, # Neue Kundensystem-ID zurückmelden
	                ),
	                fints.segments.message.HNSHA2( # Signaturabschluss, version 2
	                    header = fints.formals.SegmentHeader('HNSHA', 6, 2), # Segmentkopf
	                    security_reference = '2460121', # Sicherheitskontrollreferenz
	                    user_defined_signature = fints.formals.UserDefinedSignature( # Benutzerdefinierte Signatur
	                            pin = '***',
	                        ),
	                ),
	            ]),
	    ),
	    fints.segments.message.HNHBS1( # Nachrichtenabschluss
	        header = fints.formals.SegmentHeader('HNHBS', 7, 1), # Segmentkopf
	        message_number = 1, # Nachrichtennummer
	    ),
	])

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): brokerage-hbci.consorsbank.de:443
DEBUG:urllib3.connectionpool:https://brokerage-hbci.consorsbank.de:443 "POST /hbci HTTP/1.1" 200 None
DEBUG:fints.connection:Received <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
	fints.message.FinTSInstituteMessage([
	    fints.segments.message.HNHBK3( # Nachrichtenkopf
	        header = fints.formals.SegmentHeader('HNHBK', 1, 3), # Segmentkopf
	        message_size = 172, # Größe der Nachricht (nach Verschlüsselung und Komprimierung)
	        hbci_version = 300, # HBCI-Version
	        dialog_id = '000003OT5QKKB3AI74FGRV5KV3BPV2', # Dialog-ID
	        message_number = 1, # Nachrichtennummer
	        reference_message = fints.formals.ReferenceMessage( # Bezugsnachricht
	                dialog_id = '000003OT5QKKB3AI74FGRV5KV3BPV2',
	                message_number = 1,
	            ),
	    ),
	    fints.segments.dialog.HIRMG2( # Rückmeldungen zur Gesamtnachricht
	        header = fints.formals.SegmentHeader('HIRMG', 2, 2), # Segmentkopf
	        responses = [ # Rückmeldung
	                    fints.formals.Response( # Rückmeldung
	                        code = '9800',
	                        reference_element = None,
	                        text = 'Der Dialog wurde abgebrochen.',
	                    ),
	                    fints.formals.Response( # Rückmeldung
	                        code = '9942',
	                        reference_element = None,
	                        text = 'PIN ungültig.',
	                    ),
	            ],
	    ),
	    fints.segments.message.HNHBS1( # Nachrichtenabschluss
	        header = fints.formals.SegmentHeader('HNHBS', 3, 1), # Segmentkopf
	        message_number = 1, # Nachrichtennummer
	    ),
	])

<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

Traceback (most recent call last):
  File "main.py", line 21, in <module>
    minimal_interactive_cli_bootstrap(f)
  File "/Users/MaxBethke/Library/Python/3.8/lib/python/site-packages/fints/utils.py", line 310, in minimal_interactive_cli_bootstrap
    client.fetch_tan_mechanisms()
  File "/Users/MaxBethke/Library/Python/3.8/lib/python/site-packages/fints/client.py", line 1133, in fetch_tan_mechanisms
    self._ensure_system_id()
  File "/Users/MaxBethke/Library/Python/3.8/lib/python/site-packages/fints/client.py", line 1145, in _ensure_system_id
    response = dialog.init(
  File "/Users/MaxBethke/Library/Python/3.8/lib/python/site-packages/fints/dialog.py", line 85, in init
    retval = self.send(*segments, internal_send=True)
  File "/Users/MaxBethke/Library/Python/3.8/lib/python/site-packages/fints/dialog.py", line 156, in send
    self.client.process_response_message(self, response, internal_send=internal_send)
  File "/Users/MaxBethke/Library/Python/3.8/lib/python/site-packages/fints/client.py", line 230, in process_response_message
    self._process_response(dialog, None, response)
  File "/Users/MaxBethke/Library/Python/3.8/lib/python/site-packages/fints/client.py", line 1298, in _process_response
    raise FinTSClientPINError("Error during dialog initialization, PIN wrong?")
fints.exceptions.FinTSClientPINError: Error during dialog initialization, PIN wrong?
```

**Additional context**
I am sure this is the right PIN, as I just logged in to the Consorsbank App with that.

**Comment by maxbethke** [comment]
The problem was, that as user you cant supply what you use in the online banking portal, but have to supply the "Berechtigungskennung", which typically is '<kontonummer>001'.

**Comment by comvx** [comment]
@maxbethke can you elaborate on how you got it to work with the "Berechtigungskennung"?

**Comment by maxbethke** [comment]
Hi @comvx and @party-pansen, sorry for the late reply, but I do not actively use FinTS anymore.
The essence of my comment is, that for `user_id` or `customer_id` you cant not send what the end-user would use to log into the online banking, which is what I thought. In the case of consorsbank, that would be the bank account number.

What rather has to be used is called a 'Berechtigungskennung', which typically consists of the bank account number concat with an identifier for the 'Berechtigung' (or user), which typically is '001'. Think about joint accounts for married couples for example. This is how you identify a user, in case there is more than one physical person using this bank account.

Im my case, it was `<bank account number><001>`.
I cant tell you anymore where I found the exact format for the 'Berechtigungskennung' in the case of consorsbank, but it was somewhere in the HBCI documentation.

I hope I could shed some light onto the issue.
If you are a german spreaker, [this might also help](https://wissen.consorsbank.de/t5/Sonstige-Themen/Online-Banking-mit-VR-Bank-App/td-p/22317#:~:text=Die%20Nutzerkennung%20ist%20bei%20FinTS,ist%20diese%20die%20%22001%22.)

**Comment by party-pansen** [comment]
Thanks, putting 001 after my login brings me one step further...
Unfortunately I am ending in the next error: response.code = 9010 ('Ungültiger Signaturaufbau: Fehler im Segmentaufbau.')

And fints is is throwing the error FinTSClientError("Error during dialog initialization, could not fetch BPD. Please check that you passed the correct bank identifier to the HBCI URL of the correct bank.")

Does someone have any idea? Is Consorsbank working for someone else?
