### ISSUE TITLE
"ValueError: Could not find system_id"

### ISSUE THREAD

**Issue by chuchaki** [raphaelm/python-fints#170]
**Describe the bug**
Opening the connection to the bank results in an error: ValueError: Could not find system_id, The log shows an issue with one of the banks responses

**Bank I tested this with*
Name of the bank: Kreisparkasse Herzogtum Lauenburg
FinTS URL: https://banking-sh1.s-fints-pt-sh.de/fints30

**Expected behavior**
Printed list of TAN Mechanisms

**Code required to reproduce**
```
import logging
import getpass
from datetime import date
from fints.utils import minimal_interactive_cli_bootstrap
from fints.client import FinTS3PinTanClient

logging.basicConfig(level=logging.DEBUG)
f = FinTS3PinTanClient(
    '23052750',  # Your bank's BLZ
    'LOGINNAME',  # Your login name
    getpass.getpass('PIN'),  # Your banking PIN
    'https://banking-sh1.s-fints-pt-sh.de/fints30',
    product_id='6151256F3D4F9975B877BD4A2' 
)

minimal_interactive_cli_bootstrap(f)
print(f.fetch_tan_mechanisms())
```

**Log output / error message**
```
DEBUG:fints.connection:Sending >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
        fints.message.FinTSCustomerMessage([
            fints.segments.message.HNHBK3( # Nachrichtenkopf
                header = fints.formals.SegmentHeader('HNHBK', 1, 3), # Segmentkopf
                message_size = 402, # Größe der Nachricht (nach Verschlüsselung und Komprimierung)
                hbci_version = 300, # HBCI-Version
                dialog_id = '0', # Dialog-ID
                message_number = 1, # Nachrichtennummer
            ),
            fints.segments.message.HNVSK3( # Verschlüsselungskopf, version 3
                header = fints.formals.SegmentHeader('HNVSK', 998, 3), # Segmentkopf
                security_profile = fints.formals.SecurityProfile( # Sicherheitsprofil
                        security_method = fints.formals.SecurityMethod.PIN, # Sicherheitsverfahren
                        security_method_version = 1, # Version des Sicherheitsverfahrens
                    ),
                security_function = '998', # Sicherheitsfunktion, kodiert
                security_role = fints.formals.SecurityRole.ISS, # Rolle des Sicherheitslieferanten, kodiert
                security_identification_details = fints.formals.SecurityIdentificationDetails( # Sicherheitsidentifikation, Details
                        identified_role = fints.formals.IdentifiedRole.MS,
                        cid = None,
                        identifier = '0',
                    ),
                security_datetime = fints.formals.SecurityDateTime( # Sicherheitsdatum und -uhrzeit
                        date_time_type = fints.formals.DateTimeType.STS,
                        date = datetime.date(2024, 7, 10),
                        time = datetime.time(21, 33, 8, 192646),
                    ),
                encryption_algorithm = fints.formals.EncryptionAlgorithm( # Verschlüsselungsalgorithmus
                        usage_encryption = fints.formals.UsageEncryption.OSY,
                        operation_mode = fints.formals.OperationMode.CBC,
                        encryption_algorithm = fints.formals.EncryptionAlgorithmCoded.TWOKEY3DES,
                        algorithm_parameter_value = b'\x00\x00\x00\x00\x00\x00\x00\x00',
                        algorithm_parameter_name = fints.formals.AlgorithmParameterName.KYE,
                        algorithm_parameter_iv_name = fints.formals.AlgorithmParameterIVName.IVC,
                    ),
                key_name = fints.formals.KeyName( # Schlüsselname
                        bank_identifier = fints.formals.BankIdentifier(
                                country_identifier = '280',
                                bank_code = '23052750',
                            ),
                        user_id = 'USERID',
                        key_type = fints.formals.KeyType.V, # Schlüsselart
                        key_number = 0,
                        key_version = 0,
                    ),
                compression_function = fints.formals.CompressionFunction.NULL, # Komprimierungsfunktion
            ),
            fints.segments.message.HNVSD1( # Verschlüsselte Daten, version 1
                header = fints.formals.SegmentHeader('HNVSD', 999, 1), # Segmentkopf
                data = fints.types.SegmentSequence([ # Daten, verschlüsselt
                        fints.segments.message.HNSHK4( # Signaturkopf, version 4
                            header = fints.formals.SegmentHeader('HNSHK', 2, 4), # Segmentkopf
                            security_profile = fints.formals.SecurityProfile( # Sicherheitsprofil
                                    security_method = fints.formals.SecurityMethod.PIN, # Sicherheitsverfahren
                                    security_method_version = 1, # Version des Sicherheitsverfahrens
                                ),
                            security_function = '999', # Sicherheitsfunktion, kodiert
                            security_reference = '8204964', # Sicherheitskontrollreferenz
                            security_application_area = fints.formals.SecurityApplicationArea.SHM, # Bereich der Sicherheitsapplikation, kodiert
                            security_role = fints.formals.SecurityRole.ISS, # Rolle des Sicherheitslieferanten, kodiert
                            security_identification_details = fints.formals.SecurityIdentificationDetails( # Sicherheitsidentifikation, Details
                                    identified_role = fints.formals.IdentifiedRole.MS,
                                    cid = None,
                                    identifier = '0',
                                ),
                            security_reference_number = 1, # Sicherheitsreferenznummer
                            security_datetime = fints.formals.SecurityDateTime( # Sicherheitsdatum und -uhrzeit
                                    date_time_type = fints.formals.DateTimeType.STS,
                                    date = datetime.date(2024, 7, 10),
                                    time = datetime.time(21, 33, 8, 192052),
                                ),
                            hash_algorithm = fints.formals.HashAlgorithm( # Hashalgorithmus
                                    usage_hash = '1',
                                    hash_algorithm = '999',
                                    algorithm_parameter_name = '1',
                                ),
                            signature_algorithm = fints.formals.SignatureAlgorithm( # Signaturalgorithmus
                                    usage_signature = '6',
                                    signature_algorithm = '10',
                                    operation_mode = '16',
                                ),
                            key_name = fints.formals.KeyName( # Schlüsselname
                                    bank_identifier = fints.formals.BankIdentifier(
                                            country_identifier = '280',
                                            bank_code = '23052750',
                                        ),
                                    user_id = 'USERID',
                                    key_type = fints.formals.KeyType.S, # Schlüsselart
                                    key_number = 0,
                                    key_version = 0,
                                ),
                        ),
                        fints.segments.auth.HKIDN2( # Identifikation, version 2
                            header = fints.formals.SegmentHeader('HKIDN', 3, 2), # Segmentkopf
                            bank_identifier = fints.formals.BankIdentifier( # Kreditinstitutskennung
                                    country_identifier = '280',
                                    bank_code = '23052750',
                                ),
                            customer_id = 'USERID', # Kunden-ID
                            system_id = '0', # Kundensystem-ID
                            system_id_status = fints.formals.SystemIDStatus.ID_NECESSARY, # Kundensystem-Status
                        ),
                        fints.segments.auth.HKVVB3( # Verarbeitungsvorbereitung, version 3
                            header = fints.formals.SegmentHeader('HKVVB', 4, 3), # Segmentkopf
                            bpd_version = 0, # BPD-Version
                            upd_version = 0, # UPD-Version
                            language = fints.formals.Language2.DE, # Dialogsprache
                            product_name = '6151256F3D4F9975B877BD4A2', # Produktbezeichnung
                            product_version = '4.1.0', # Produktversion
                        ),
                        fints.segments.dialog.HKSYN3( # Synchronisierung, version 3
                            header = fints.formals.SegmentHeader('HKSYN', 5, 3), # Segmentkopf
                            synchronization_mode = fints.formals.SynchronizationMode.NEW_SYSTEM_ID,
                        ),
                        fints.segments.message.HNSHA2( # Signaturabschluss, version 2
                            header = fints.formals.SegmentHeader('HNSHA', 6, 2), # Segmentkopf
                            security_reference = '8204964', # Sicherheitskontrollreferenz
                            user_defined_signature = fints.formals.UserDefinedSignature( # Benutzerdefinierte Signatur
                                    pin = '***',
                                ),
                        ),
                    ]),
            ),
            fints.segments.message.HNHBS1( # Nachrichtenabschluss
                header = fints.formals.SegmentHeader('HNHBS', 7, 1), # Segmentkopf
                message_number = 1, # Nachrichtennummer
            ),
        ])

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): banking-sh1.s-fints-pt-sh.de:443
DEBUG:urllib3.connectionpool:https://banking-sh1.s-fints-pt-sh.de:443 "POST /fints30 HTTP/1.1" 200 238
DEBUG:fints.connection:Received <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
        fints.message.FinTSInstituteMessage([
            fints.segments.message.HNHBK3( # Nachrichtenkopf
                header = fints.formals.SegmentHeader('HNHBK', 1, 3), # Segmentkopf
                message_size = 174, # Größe der Nachricht (nach Verschlüsselung und Komprimierung)
                hbci_version = 300, # HBCI-Version
                dialog_id = '0', # Dialog-ID
                message_number = 1, # Nachrichtennummer
                reference_message = fints.formals.ReferenceMessage( # Bezugsnachricht
                        dialog_id = '0',
                        message_number = 1,
                    ),
            ),
            fints.segments.dialog.HIRMG2( # Rückmeldungen zur Gesamtnachricht
                header = fints.formals.SegmentHeader('HIRMG', 2, 2), # Segmentkopf
                responses = [ # Rückmeldung
                            fints.formals.Response( # Rückmeldung
                                code = '9050',
                                reference_element = None,
                                text = 'Die Nachricht enthält Fehler.',
                            ),
                            fints.formals.Response( # Rückmeldung
                                code = '9800',
                                reference_element = None,
                                text = 'Dialog abgebrochen',
                            ),
                            fints.formals.Response( # Rückmeldung
                                code = '9110',
                                reference_element = None,
                                text = 'Ungültige Auftragsnachricht: Unbekannter Aufbau.',
                            ),
                    ],
            ),
            fints.segments.message.HNHBS1( # Nachrichtenabschluss
                header = fints.formals.SegmentHeader('HNHBS', 3, 1), # Segmentkopf
                message_number = 1, # Nachrichtennummer
            ),
        ])

<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

DEBUG:fints.connection:Sending >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
        fints.message.FinTSCustomerMessage([
            fints.segments.message.HNHBK3( # Nachrichtenkopf
                header = fints.formals.SegmentHeader('HNHBK', 1, 3), # Segmentkopf
                message_size = 310, # Größe der Nachricht (nach Verschlüsselung und Komprimierung)
                hbci_version = 300, # HBCI-Version
                dialog_id = '0', # Dialog-ID
                message_number = 2, # Nachrichtennummer
            ),
            fints.segments.message.HNVSK3( # Verschlüsselungskopf, version 3
                header = fints.formals.SegmentHeader('HNVSK', 998, 3), # Segmentkopf
                security_profile = fints.formals.SecurityProfile( # Sicherheitsprofil
                        security_method = fints.formals.SecurityMethod.PIN, # Sicherheitsverfahren
                        security_method_version = 1, # Version des Sicherheitsverfahrens
                    ),
                security_function = '998', # Sicherheitsfunktion, kodiert
                security_role = fints.formals.SecurityRole.ISS, # Rolle des Sicherheitslieferanten, kodiert
                security_identification_details = fints.formals.SecurityIdentificationDetails( # Sicherheitsidentifikation, Details
                        identified_role = fints.formals.IdentifiedRole.MS,
                        cid = None,
                        identifier = '0',
                    ),
                security_datetime = fints.formals.SecurityDateTime( # Sicherheitsdatum und -uhrzeit
                        date_time_type = fints.formals.DateTimeType.STS,
                        date = datetime.date(2024, 7, 10),
                        time = datetime.time(21, 33, 8, 405318),
                    ),
                encryption_algorithm = fints.formals.EncryptionAlgorithm( # Verschlüsselungsalgorithmus
                        usage_encryption = fints.formals.UsageEncryption.OSY,
                        operation_mode = fints.formals.OperationMode.CBC,
                        encryption_algorithm = fints.formals.EncryptionAlgorithmCoded.TWOKEY3DES,
                        algorithm_parameter_value = b'\x00\x00\x00\x00\x00\x00\x00\x00',
                        algorithm_parameter_name = fints.formals.AlgorithmParameterName.KYE,
                        algorithm_parameter_iv_name = fints.formals.AlgorithmParameterIVName.IVC,
                    ),
                key_name = fints.formals.KeyName( # Schlüsselname
                        bank_identifier = fints.formals.BankIdentifier(
                                country_identifier = '280',
                                bank_code = '23052750',
                            ),
                        user_id = '',
                        key_type = fints.formals.KeyType.V, # Schlüsselart
                        key_number = 0,
                        key_version = 0,
                    ),
                compression_function = fints.formals.CompressionFunction.NULL, # Komprimierungsfunktion
            ),
            fints.segments.message.HNVSD1( # Verschlüsselte Daten, version 1
                header = fints.formals.SegmentHeader('HNVSD', 999, 1), # Segmentkopf
                data = fints.types.SegmentSequence([ # Daten, verschlüsselt
                        fints.segments.message.HNSHK4( # Signaturkopf, version 4
                            header = fints.formals.SegmentHeader('HNSHK', 2, 4), # Segmentkopf
                            security_profile = fints.formals.SecurityProfile( # Sicherheitsprofil
                                    security_method = fints.formals.SecurityMethod.PIN, # Sicherheitsverfahren
                                    security_method_version = 1, # Version des Sicherheitsverfahrens
                                ),
                            security_function = '999', # Sicherheitsfunktion, kodiert
                            security_reference = '7077734', # Sicherheitskontrollreferenz
                            security_application_area = fints.formals.SecurityApplicationArea.SHM, # Bereich der Sicherheitsapplikation, kodiert
                            security_role = fints.formals.SecurityRole.ISS, # Rolle des Sicherheitslieferanten, kodiert
                            security_identification_details = fints.formals.SecurityIdentificationDetails( # Sicherheitsidentifikation, Details
                                    identified_role = fints.formals.IdentifiedRole.MS,
                                    cid = None,
                                    identifier = '0',
                                ),
                            security_reference_number = 1, # Sicherheitsreferenznummer
                            security_datetime = fints.formals.SecurityDateTime( # Sicherheitsdatum und -uhrzeit
                                    date_time_type = fints.formals.DateTimeType.STS,
                                    date = datetime.date(2024, 7, 10),
                                    time = datetime.time(21, 33, 8, 404783),
                                ),
                            hash_algorithm = fints.formals.HashAlgorithm( # Hashalgorithmus
                                    usage_hash = '1',
                                    hash_algorithm = '999',
                                    algorithm_parameter_name = '1',
                                ),
                            signature_algorithm = fints.formals.SignatureAlgorithm( # Signaturalgorithmus
                                    usage_signature = '6',
                                    signature_algorithm = '10',
                                    operation_mode = '16',
                                ),
                            key_name = fints.formals.KeyName( # Schlüsselname
                                    bank_identifier = fints.formals.BankIdentifier(
                                            country_identifier = '280',
                                            bank_code = '23052750',
                                        ),
                                    user_id = 'USERID',
                                    key_type = fints.formals.KeyType.S, # Schlüsselart
                                    key_number = 0,
                                    key_version = 0,
                                ),
                        ),
                        fints.segments.dialog.HKEND1( # Dialogende, version 1
                            header = fints.formals.SegmentHeader('HKEND', 3, 1), # Segmentkopf
                            dialog_id = '0', # Dialog-ID
                        ),
                        fints.segments.message.HNSHA2( # Signaturabschluss, version 2
                            header = fints.formals.SegmentHeader('HNSHA', 4, 2), # Segmentkopf
                            security_reference = '7077734', # Sicherheitskontrollreferenz
                            user_defined_signature = fints.formals.UserDefinedSignature( # Benutzerdefinierte Signatur
                                    pin = '***',
                                ),
                        ),
                    ]),
            ),
            fints.segments.message.HNHBS1( # Nachrichtenabschluss
                header = fints.formals.SegmentHeader('HNHBS', 5, 1), # Segmentkopf
                message_number = 2, # Nachrichtennummer
            ),
        ])

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

DEBUG:urllib3.connectionpool:https://banking-sh1.s-fints-pt-sh.de:443 "POST /fints30 HTTP/1.1" 200 458
DEBUG:fints.connection:Received <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
        fints.message.FinTSInstituteMessage([
            fints.segments.message.HNHBK3( # Nachrichtenkopf
                header = fints.formals.SegmentHeader('HNHBK', 1, 3), # Segmentkopf
                message_size = 334, # Größe der Nachricht (nach Verschlüsselung und Komprimierung)
                hbci_version = 300, # HBCI-Version
                dialog_id = '0', # Dialog-ID
                message_number = 2, # Nachrichtennummer
                reference_message = fints.formals.ReferenceMessage( # Bezugsnachricht
                        dialog_id = '0',
                        message_number = 2,
                    ),
            ),
            fints.segments.message.HNVSK3( # Verschlüsselungskopf, version 3
                header = fints.formals.SegmentHeader('HNVSK', 998, 3), # Segmentkopf
                security_profile = fints.formals.SecurityProfile( # Sicherheitsprofil
                        security_method = fints.formals.SecurityMethod.PIN, # Sicherheitsverfahren
                        security_method_version = 1, # Version des Sicherheitsverfahrens
                    ),
                security_function = '998', # Sicherheitsfunktion, kodiert
                security_role = fints.formals.SecurityRole.ISS, # Rolle des Sicherheitslieferanten, kodiert
                security_identification_details = fints.formals.SecurityIdentificationDetails( # Sicherheitsidentifikation, Details
                        identified_role = fints.formals.IdentifiedRole.MR,
                        cid = None,
                        identifier = '0',
                    ),
                security_datetime = fints.formals.SecurityDateTime( # Sicherheitsdatum und -uhrzeit
                        date_time_type = fints.formals.DateTimeType.STS,
                    ),
                encryption_algorithm = fints.formals.EncryptionAlgorithm( # Verschlüsselungsalgorithmus
                        usage_encryption = fints.formals.UsageEncryption.OSY,
                        operation_mode = fints.formals.OperationMode.CBC,
                        encryption_algorithm = fints.formals.EncryptionAlgorithmCoded.TWOKEY3DES,
                        algorithm_parameter_value = b'\x00\x00\x00\x00\x00\x00\x00\x00',
                        algorithm_parameter_name = fints.formals.AlgorithmParameterName.KYE,
                        algorithm_parameter_iv_name = fints.formals.AlgorithmParameterIVName.IVC,
                    ),
                key_name = fints.formals.KeyName( # Schlüsselname
                        bank_identifier = fints.formals.BankIdentifier(
                                country_identifier = '280',
                                bank_code = '23052750',
                            ),
                        user_id = 'USERID',
                        key_type = fints.formals.KeyType.V, # Schlüsselart
                        key_number = 0,
                        key_version = 0,
                    ),
                compression_function = fints.formals.CompressionFunction.NULL, # Komprimierungsfunktion
            ),
            fints.segments.message.HNVSD1( # Verschlüsselte Daten, version 1
                header = fints.formals.SegmentHeader('HNVSD', 999, 1), # Segmentkopf
                data = fints.types.SegmentSequence([ # Daten, verschlüsselt
                        fints.segments.message.HNSHK4( # Signaturkopf, version 4
                            header = fints.formals.SegmentHeader('HNSHK', 2, 4), # Segmentkopf
                            security_profile = fints.formals.SecurityProfile( # Sicherheitsprofil
                                    security_method = fints.formals.SecurityMethod.PIN, # Sicherheitsverfahren
                                    security_method_version = 1, # Version des Sicherheitsverfahrens
                                ),
                            security_function = '999', # Sicherheitsfunktion, kodiert
                            security_reference = '7077734', # Sicherheitskontrollreferenz
                            security_application_area = fints.formals.SecurityApplicationArea.SHM, # Bereich der Sicherheitsapplikation, kodiert
                            security_role = fints.formals.SecurityRole.ISS, # Rolle des Sicherheitslieferanten, kodiert
                            security_identification_details = fints.formals.SecurityIdentificationDetails( # Sicherheitsidentifikation, Details
                                    identified_role = fints.formals.IdentifiedRole.MR,
                                    cid = None,
                                    identifier = '0',
                                ),
                            security_reference_number = 1, # Sicherheitsreferenznummer
                            security_datetime = fints.formals.SecurityDateTime( # Sicherheitsdatum und -uhrzeit
                                    date_time_type = fints.formals.DateTimeType.STS,
                                ),
                            hash_algorithm = fints.formals.HashAlgorithm( # Hashalgorithmus
                                    usage_hash = '1',
                                    hash_algorithm = '999',
                                    algorithm_parameter_name = '1',
                                ),
                            signature_algorithm = fints.formals.SignatureAlgorithm( # Signaturalgorithmus
                                    usage_signature = '6',
                                    signature_algorithm = '10',
                                    operation_mode = '16',
                                ),
                            key_name = fints.formals.KeyName( # Schlüsselname
                                    bank_identifier = fints.formals.BankIdentifier(
                                            country_identifier = '280',
                                            bank_code = '23052750',
                                        ),
                                    user_id = 'USERID',
                                    key_type = fints.formals.KeyType.S, # Schlüsselart
                                    key_number = 0,
                                    key_version = 0,
                                ),
                        ),
                        fints.segments.dialog.HIRMG2( # Rückmeldungen zur Gesamtnachricht
                            header = fints.formals.SegmentHeader('HIRMG', 3, 2), # Segmentkopf
                            responses = [ # Rückmeldung
                                        fints.formals.Response( # Rückmeldung
                                            code = '0010',
                                            reference_element = None,
                                            text = 'Nachricht entgegengenommen.',
                                        ),
                                        fints.formals.Response( # Rückmeldung
                                            code = '0100',
                                            reference_element = None,
                                            text = 'Dialog beendet.',
                                        ),
                                ],
                        ),
                        fints.segments.message.HNSHA2( # Signaturabschluss, version 2
                            header = fints.formals.SegmentHeader('HNSHA', 4, 2), # Segmentkopf
                            security_reference = '7077734', # Sicherheitskontrollreferenz
                        ),
                    ]),
            ),
            fints.segments.message.HNHBS1( # Nachrichtenabschluss
                header = fints.formals.SegmentHeader('HNHBS', 5, 1), # Segmentkopf
                message_number = 2, # Nachrichtennummer
            ),
        ])
```
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

Traceback (most recent call last):
  File "/home/till/Projects/FinTS Playground/test.py", line 18, in <module>
    print(f.fetch_tan_mechanisms())
  File "/home/till/.local/lib/python3.10/site-packages/fints/client.py", line 1156, in fetch_tan_mechanisms
    self._ensure_system_id()
  File "/home/till/.local/lib/python3.10/site-packages/fints/client.py", line 1174, in _ensure_system_id
    raise ValueError('Could not find system_id')
ValueError: Could not find system_id

**Additional context**
None

**Comment by chuchaki** [comment]
Found a typo in my credentials file, sorry :-)

Thanks for the software !
