### ISSUE TITLE
ING DIBA not working

### ISSUE THREAD

**Issue by UweZiegenhagen** [raphaelm/python-fints#18]
When trying working code (for Sparkasse) with ING Diba settings I am getting an error:

```
runfile('D:/fints/test_ing.py', wdir='D:/fints')
Traceback (most recent call last):

  File "<ipython-input-4-ea5e7ac4ce2a>", line 1, in <module>
    runfile('D:/fints/test_ing.py', wdir='D:/fints')

  File "C:\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 692, in runfile
    execfile(filename, namespace)

  File "C:\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 101, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "D:/fints/test_ing.py", line 15, in <module>
    accounts = f.get_sepa_accounts()

  File "C:\Anaconda3\lib\site-packages\fints-0.2.1-py3.5.egg\fints\client.py", line 33, in get_sepa_accounts
    dialog.sync()

  File "C:\Anaconda3\lib\site-packages\fints-0.2.1-py3.5.egg\fints\dialog.py", line 41, in sync
    resp = self.send(msg_sync)

  File "C:\Anaconda3\lib\site-packages\fints-0.2.1-py3.5.egg\fints\dialog.py", line 99, in send
    raise FinTSDialogError(resp.get_summary_by_segment('HIRMG'))

FinTSDialogError: {'9110': 'Unbekanntes Kreditinstitut.', '9800': 'Der Dialog wurde abgebrochen.'}
```

Is there something I can do?

**Comment by UweZiegenhagen** [comment]
Problem was in front of the machine, connection problem could be solved.
