### ISSUE TITLE
Sparkasse get_holdings error 'message contains an error'

### ISSUE THREAD

**Issue by fipso** [raphaelm/python-fints#24]
```
Traceback (most recent call last):
  File "oblogin.py", line 16, in <module>
    holdings = f.get_holdings(accounts[0])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\fints-0.2.1-py3.6.egg\fints\client.py", line 198, in get_holdings
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\fints-0.2.1-py3.6.egg\fints\dialog.py", line 110, in send
fints.dialog.FinTSDialogError: {'9050': 'Die Nachricht enthält Fehler.'}

```

**Comment by jahir** [comment]
Same with Volksbank in der Ortenau (66490000), which is using Fiducia:
```
[...]
INFO:fints.dialog:Sending Message
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): hbci11.fiducia.de
DEBUG:urllib3.connectionpool:https://hbci11.fiducia.de:443 "POST /cgi-bin/hbciservlet HTTP/1.1" 200 614
Traceback (most recent call last):
  File "./client.py", line 32, in <module>
    holdings = f.get_holdings(accounts[0])
  File "/usr/local/lib/python3.6/site-packages/fints/client.py", line 177, in get_holdings
    resp = dialog.send(msg)
  File "/usr/local/lib/python3.6/site-packages/fints/dialog.py", line 99, in send
    raise FinTSDialogError(resp.get_summary_by_segment('HIRMG'))
fints.dialog.FinTSDialogError: {'9050': 'Die Nachricht enthält Fehler.'}
```

**Comment by raphaelm** [comment]
Probably obsolete since release of 2.0
