### ISSUE TITLE
Error during pip install

### ISSUE THREAD

**Issue by zoranzaric** [raphaelm/python-fints#3]
See the logfile:

[pip.log.txt](https://github.com/raphaelm/python-fints/files/691615/pip.log.txt)

**Comment by raphaelm** [comment]
Will fix that, thanks. Should only happen with source install, if you install ``wheel`` first and have a recent pip version, it should work.

**Comment by raphaelm** [comment]
I just published a 0.1.1 that should fix the problem

**Comment by zoranzaric** [comment]
Now I'm getting:

```
Using version 0.1.1 (newest of versions: 0.1.1, 0.1.0)
  Downloading fints-0.1.1.tar.gz
  Downloading from URL https://pypi.python.org/packages/79/3f/7db6e6009f86cec22a6c173dcba85107c49fcc8a7f5d8b5613500a7e588c/fints-0.1.1.tar.gz#md5=ed5112ae9895d0a5a71948a7f4f643bc (from https://pypi.python.org/simple/fints/)
  Running setup.py (path:/home/zz/workspaces/fetch-transactions/.virtualenv/build/fints/setup.py) egg_info for package fints
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/home/zz/workspaces/fetch-transactions/.virtualenv/build/fints/setup.py", line 41, in <module>
        packages=find_packages(include=['fints', 'fints.*']),
    TypeError: find_packages() got an unexpected keyword argument 'include'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/home/zz/workspaces/fetch-transactions/.virtualenv/build/fints/setup.py", line 41, in <module>

    packages=find_packages(include=['fints', 'fints.*']),

TypeError: find_packages() got an unexpected keyword argument 'include'
```

**Comment by raphaelm** [comment]
Okay, please try a non-ancient version of the environment first, e.g. ``pip install -U pip wheel setuptools`` inside your virtual environment, pip 1.5.4 is three years old and a lot got better in pip 6.0+.
