### ISSUE TITLE
JSON output

### ISSUE THREAD

**Issue by timaschew** [raphaelm/python-fints#39]
Hi, first of all thanks you for this great library!

I tried to save the output in JSON, with this code snippet, but get errors

`pprint(json.dumps(statements[0].__dict__))`

```
Traceback (most recent call last):
  File "bank-account.py", line 21, in <module>
    pprint(json.dumps(statements[0].__dict__))
  File "/usr/lib/python3.5/json/__init__.py", line 230, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.5/json/encoder.py", line 198, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.5/json/encoder.py", line 256, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.5/json/encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <-76.48 EUR> is not JSON serializable
```

**Comment by raphaelm** [comment]
This is more of a problem with the ``mt-940`` package than with this one. However, the large open PR in this repo might resolve it for the future.
