### ISSUE TITLE
Haspa base64/encoding issues

### ISSUE THREAD

**Issue by kpcyrd** [raphaelm/python-fints#81]
Haspa updated their online banking around Easter, it seems this broke python-fints. I'm now getting this exception which seems to be due to encoding issues in their api response:
```
 Traceback (most recent call last):
   File "/usr/lib/python3.7/base64.py", line 37, in _bytes_from_decode_data
     return s.encode('ascii')
 UnicodeEncodeError: 'ascii' codec can't encode characters in position 127-128: ordinal not in range(128)
 During handling of the above exception, another exception occurred:
 Traceback (most recent call last):
   File "/usr/lib/python3.7/site-packages/fints/dialog.py", line 72, in init
     retval = self.send(*segments, internal_send=True)
   File "/usr/lib/python3.7/site-packages/fints/dialog.py", line 114, in send
     response = self.client.connection.send(message)
   File "/usr/lib/python3.7/site-packages/fints/connection.py", line 32, in send
     response = base64.b64decode(r.content.decode('iso-8859-1'))
   File "/usr/lib/python3.7/base64.py", line 80, in b64decode
     s = _bytes_from_decode_data(s)
   File "/usr/lib/python3.7/base64.py", line 39, in _bytes_from_decode_data
     raise ValueError('string argument should contain only ASCII characters')
 ValueError: string argument should contain only ASCII characters
 The above exception was the direct cause of the following exception:
 Traceback (most recent call last):
   File "/redacted.py", line 150, in <module>
     main(sock, path, acc)
   File "/redacted.py", line 82, in main
     balance = get_balance(acc, **config)
   File "/redacted.py", line 31, in get_balance
     accounts = f.get_sepa_accounts()
   File "/usr/lib/python3.7/site-packages/fints/client.py", line 414, in get_sepa_accounts
     with self._get_dialog() as dialog:
   File "/usr/lib/python3.7/site-packages/fints/client.py", line 254, in _get_dialog
     self._ensure_system_id()
   File "/usr/lib/python3.7/site-packages/fints/client.py", line 1053, in _ensure_system_id
     HKSYN3(SynchronizationMode.NEW_SYSTEM_ID),
   File "/usr/lib/python3.7/site-packages/fints/dialog.py", line 80, in init
     raise FinTSDialogInitError("Couldn't establish dialog with bank, Authentication data wrong?") from e
 fints.exceptions.FinTSDialogInitError: Couldn't establish dialog with bank, Authentication data wrong?
```

**Comment by kpcyrd** [comment]
ok, it seems the fints endpoint changed to `https://banking-hh7.s-fints-pt-hh.de/fints30`.
