### ISSUE TITLE
ValueError: Could not find system_id

### ISSUE THREAD

**Issue by yunocare** [raphaelm/python-fints#86]
Hi there,

I am trying to establish a connection to my Sparkasse bank account with the following script I have found on the internet (and inserted my account login data correctly).
Why does the "ValueError: Could not find system_id" error occur?

My script _fints-gs.py_ currently looks like this:

```
#!/usr/bin/python3
import re
import pymysql
import hashlib
import time
import smtplib
import datetime
from decimal import *
from email.mime.text import MIMEText
from fints.client import FinTS3PinTanClient

blz = '51050015'
account = '12347897234832'
pin = '123'
endpoint = 'https://banking-sn4.s-fints-pt-sn.de/fints30'
mysqlhost = '127.0.0.1'
mysqluser = 'root'
mysqlpass = ''
mysqldb = 'naspa'
mailsender = 'banking@myserver.de'
mailreceiver = 'xxx@yyy.de'
mailserver = '127.0.0.1'
mailsubject = 'Kontobewegung!'

def mailtransfer(mailtext):
    message = ''
    message = message + mailtext

    msg = MIMEText(message, _charset="UTF-8")
    msg['Subject'] = mailsubject
    msg['From'] = mailsender
    msg['To'] = mailreceiver

    s = smtplib.SMTP(mailserver)
    s.send_message(msg)
    s.quit()

# Connect to the database
conn = pymysql.connect(host = mysqlhost, user = mysqluser, passwd = mysqlpass, db = mysqldb)

# Connect to the bank
print('BLZ: ' + blz)
print('Endpoint: ' + endpoint)
f = FinTS3PinTanClient(blz, account, pin, endpoint)



accounts = f.get_sepa_accounts()


# already tried:
#f.set_tan_mechanism('900')
#with f:
# accounts = f.get_sepa_accounts()
# print(f.get_balance(accounts[0]))
# print(f.get_transactions(accounts[0]))
#with f:
#    accounts = f.get_sepa_accounts()
#    txns = f.get_transactions(accounts[0])
#
#pprint.pprint(txns)


# Get all acounts
#with f:
#  f.get_sepa_accounts()
#konten = f.get_sepa_accounts()

# Get all Statements
# (We only get a few months anyway!)
bewegungen = f.get_statement(konten[0], datetime.date(2010, 10, 1), datetime.date.today())

# Loop through all statements
inserted = 0
for bewegung in bewegungen:
    # Hash this statement data
    myhash = ''
    myhash += str(bewegung.data.get('transaction_code', ''))
    myhash += str(bewegung.data.get('transaction_details', ''))
    myhash += str(bewegung.data.get('prima_nota', ''))
    myhash += str(bewegung.data.get('applicant_name', ''))
    myhash += str(bewegung.data.get('customer_reference', ''))
    myhash += str(bewegung.data.get('extra_details', ''))
    myhash += str(bewegung.data.get('purpose', ''))
    myhash += str(bewegung.data.get('additional_purpose', ''))
    myhash += str(bewegung.data.get('applicant_bin', ''))
    myhash += str(bewegung.data.get('applicant_iban', ''))
    myhash += str(bewegung.data.get('funds_code', ''))
    myhash += str(bewegung.data.get('date', ''))
    myhash += str(bewegung.data.get('return_debit_notes', ''))
    myhash += str(bewegung.data.get('status', ''))
    myhash += str(bewegung.data.get('currency', ''))
    myhash += str(bewegung.data.get('posting_text', ''))
    myhash += str(bewegung.data.get('recipient_name', ''))
    myhash += str(bewegung.data.get('bank_reference', ''))
    myhash += str(bewegung.data.get('amount', ''))
    myhash += str(bewegung.data.get('entry_date', ''))
    myhash += str(bewegung.data.get('id', '')) 
    myhash = hashlib.sha512(myhash.encode('UTF-8')).hexdigest()

    # Check if we already got this hash
    cur = conn.cursor()
    query = "SELECT 1 from kontobewegungen where hash = '" + myhash + "';"
    cur.execute(query)

    rowcount = cur.rowcount
    if rowcount == 0:
        # Get the amount (some Regexp needs to be done here, because it is something like '<-1.65 EUR>')
        amount = ''
        p = re.compile('[-+]?\d*\.\d+|[-+]?\d+')
        m = p.search(str(bewegung.data['amount']))
        amount = m.group()
        # Check if it's for the feature (amount is only requested, not yet really booked!)
        onlyrequested = 0
        bookingdate = datetime.datetime.strptime(str(bewegung.data.get('date', '')), '%Y-%m-%d').date()
        if bookingdate > datetime.date.today():
            onlyrequested = 1
        # Insert it!
        cur = conn.cursor()
        query = ''
        query += "INSERT INTO kontobewegungen (hash, onlyrequested, transaction_code, transaction_details, prima_nota, applicant_name, customer_reference, extra_details,"
        query += "purpose, additional_purpose, applicant_bin, applicant_iban, funds_code, date, return_debit_notes, status, currency, "
        query += "posting_text, recipient_name, bank_reference, amount, entry_date, id) "
        query += "VALUES ('" + myhash + "', " + str(onlyrequested) + ", '" + str(bewegung.data.get('transaction_code', '')) + "', '" +str(bewegung.data.get('transaction_details', '')) + "', '"+ str(bewegung.data.get('prima_nota', '')) + "', '"
        query += str(bewegung.data.get('applicant_name', '')) + "', '" + str(bewegung.data.get('customer_reference', '')) + "', '" + str(bewegung.data.get('extra_details', '')) + "', '"
        query += str(bewegung.data.get('purpose', '')) + "', '" + str(bewegung.data.get('additional_purpose', '')) + "', '" + str(bewegung.data.get('applicant_bin', '')) + "', '"
        query += str(bewegung.data.get('applicant_iban', '')) + "', '" + str(bewegung.data.get('funds_code', '')) + "', '" + str(bewegung.data.get('date', '')) + "', '"
        query += str(bewegung.data.get('return_debit_notes', '')) + "', '" + str(bewegung.data.get('status', '')) + "', '" + str(bewegung.data.get('currency', '')) + "', '"
        query += str(bewegung.data.get('posting_text', '')) + "', '" + str(bewegung.data.get('recipient_name', ''))+ "', '" + str(bewegung.data.get('bank_reference', '')) + "', '"
        query += str(amount) + "', '" + str(bewegung.data.get('entry_date', '')) + "', '" + str(bewegung.data.get('id', '')) + "');"
        cur.execute(query)
        conn.commit()
        inserted = inserted + 1
        # Mail it
        mailtext = ''
        if onlyrequested == 1:
            mailtext += "ACHTUNG: VORABBUCHUNG\n\n"
        mailtext += str(bewegung.data)
        mailtransfer(mailtext)

# Now get the Balance, and add it to every balance colum which is still empty from behind
endbalance = f.get_balance(konten[0])
p = re.compile('[-+]?\d*\.\d+|[-+]?\d+')
m = p.search(str(endbalance))
endbalance = m.group()

amountbefore = Decimal(endbalance)
bewegungsamountbefore = 0

cur = conn.cursor()
query = 'SELECT bewegid, amount FROM kontobewegungen WHERE balance = 0 AND onlyrequested = 0 ORDER BY bewegid DESC;'
cur.execute(query)
for row in cur.fetchall():
    bewegid = row[0]
    # Calculate balance
    balance = amountbefore - bewegungsamountbefore
    
    # Update the balance in the database
    cur2 = conn.cursor()
    query = 'UPDATE kontobewegungen SET balance = ' + str(balance) + ' WHERE bewegid = ' + str(bewegid) + ';'
    cur2.execute(query)
    conn.commit()
    
    # Update the fields
    bewegungsamountbefore = row[1]
    amountbefore = balance
   
print(time.strftime("%d.%m.%Y %H:%M:%S") + ': Inserted: ' + str(inserted) + '     Balance: ' + str(endbalance) + ' EUR')        
conn.close()
```

When executing the script, I get the following output on my console:

`$ ./fints-gs.py 
BLZ: 51050015
Endpoint: https://banking-sn4.s-fints-pt-sn.de/fints30
Traceback (most recent call last):
  File "./fints-gs.py", line 48, in <module>
    accounts = f.get_sepa_accounts()
  File "/home/yunocare/.local/lib/python3.6/site-packages/fints/client.py", line 414, in get_sepa_accounts
    with self._get_dialog() as dialog:
  File "/home/yunocare/.local/lib/python3.6/site-packages/fints/client.py", line 254, in _get_dialog
    self._ensure_system_id()
  File "/home/yunocare/.local/lib/python3.6/site-packages/fints/client.py", line 1058, in _ensure_system_id
    raise ValueError('Could not find system_id')
ValueError: Could not find system_id`

I am new to python and would like to ask if you can please provide help on this error?

**Comment by raphaelm** [comment]
This looks like you're using the wrong API endpoint. Nassauische Spaarkasse is on ``https://banking-hs7.s-fints-pt-hs.de/fints30``.
